LATEST_NEWS_URL = 'https://api.currentsapi.services/v1/latest-news'
SEARCH_URL = 'https://api.currentsapi.services/v1/search'

AVAILABLE_COUNTRY = ["AS", "AT", "BD", "BR", "CA", "CN", "FI","FR", "DE", "HK", "IN", "ID", "IL", "JP", "PH", "MX", "MY", "NL", "NO", "NZ", "PT",
     "RU", "SA", "SG", "CH", "SK", "TW", "TH", "VIET", "AE", "US", "GB", "VEN", "ZW", "IT", "PSE"]

REGION_MAPPING = {
    "Australia": "AS", 
    "Austria": "AT", 
    "Bangladesh": "BD", 
    "Brazil": "BR", 
    "Canada": "CA", 
    "China": "CN", 
    "Finland": "FI",
    "France":"FR", 
    "Denmark": "DE", 
    "Hong Kong": "HK", 
    "India": "IN", 
    "Indonedia": "ID", 
    "Israel": "IL", 
    "Japan": "JP", 
    "Philippines": "PH", 
    "Mexico": "MX", 
    "Malaysia": "MY", 
    "Dutch": "NL", 
    "Norway": "NO", 
    "New Zealand": "NZ", 
    "Portugal": "PT",
    "Russia": "RU", 
    "Saudi Arabia": "SA", 
    "Singapore": "SG", 
    "Switzerland": "CH", 
    "South Korea": "SK", 
    "Taiwan": "TW", 
    "Thailand": "TH", 
    "Vietnam": "VIET", 
    "United Arab Emirates": "AE", 
    "United State": "US", 
    "German": "GB", 
    "Venuzeula": "VEN", 
    "Zimbabwe": "ZW", 
    "Italy": "IT", 
    "Palestine": "PSE"
}


AVAILABLE_LANGUAGE = [ "ar", "es", "de", "nl", "en", "hi","fi","fr", "it", "pt", "ja", "msa", "ru", "zh", "ko"]

LANGUAGE_MAPPING = {
    'Arabic':'ar',
    'Chinese':'zh',
    'Dutch':'nl',
    'English':'en',
    'Finnish':'fi',
    'French':'fr',
    'German':'de',
    'Hindi':'hi',
    'Italian':'it',
    'Japanese':'ja',
    'Korean':'ko',
    'Malay':'msa',
    'Portuguese':'pt',
    'Russian':'ru',
    'Spanish':'es',
}

VALID_CATEGORIES = [
    'regional',
    'technology',
    'lifestyle',
    'business',
    'general',
    'programming',
    'science',
    'entertainment',
    'world',
    'sports',
    'finance',
    'academia',
    'politics',
    'health',
    'opinion',
    'food',
    'game',
    'fashion',
    'academic',
    'crap',
    'travel',
    'culture',
    'economy',
    'environment',
    'art',
    'music',
    'notsure',
    'CS',
    'education',
    'redundant',
    'television',
    'commodity',
    'movie',
    'entrepreneur',
    'review',
    'auto',
    'energy',
    'celebrity',
    'medical',
    'gadgets',
    'design',
    'EE',
    'security',
    'mobile',
    'estate',
    'funny'
]

sort_method = {'start_date','page_number','end_date'}
