
VERSION = 'v1'

DOMAIN = 'api.currentsapi.services'

LATEST_NEWS_URL = 'https://%s/%s/latest-news'
SEARCH_URL = 'https://%s/%s/search'

REGION_MAPPING = {
	"United State": "US", 
	"Taiwan": "TW",
	"German": "DE", 
	"United Kingdom": "GB",
	"China": "CN", 
	"India": "IN", 
	"Spain": "ES",
	"Italy": "IT", 
	"Poland": "PL",	
	"Australia": "AU", 
	"Malaysia": "MY", 
	"Singapore": "SG", 
	"Canada": "CA", 
	"South Korea": "KR", 
	"Denmark": "DK", 
	"France":"FR", 
	"Belgium": "BE",
	"Japan": "JP", 
	"Austria": "AT",
	"Portugal": "PT",
	"Philippines": "PH", 
	"Hong Kong": "HK",
	"Argentina": "AR",
	"Venezuela": "VE", 
	"Brazil": "BR", 
	"Finland": "FI",
	"Indonedia": "ID", 
	"Vietnam": "VN",
	"Mexico": "MX", 
	"Greece": "GR",
	"Netherlands": "NL", 
	"Norway": "NO", 
	"New Zealand": "NZ", 
	"Russia": "RU", 
	"Saudi-Arabia": "SA", 
	"Switzerland": "CH", 
	"Thailand": "TH", 
	"United Arab Emirates": "AE", 
	"Ireland": "IE", 
	"Iran": "IR",
	"Iraq": "IQ",
	"Romania": "RO",
	"Afghanistan": "AF",
	"Zimbabwe": "ZW", 
	"Myanmar": "MM",
	"Sweden": "SE", 
	"Peru": "PE",
	"Panama": "PA",
	"Egypt": "EG",
	"Turkey": "TR",
	"Israel": "IL",
	"Czech Republic": "CZ",	
	"Bangladesh": "BD",
	"Nigeria": "NG",
	"Kenya": "KE",
	"Chile": "CL",
	"Uruguay": "UY",
	"Ecuador": "EC",
	"Serbia": "RS",
	"Hungary":"HU",
	"Slovenia": "SI",
	"Gahana": "GH",
	"Bolivia": "BO",
	"Pakistan":"PK",
	"Colombia": "CO",
	"North Korea": "NK",
	"Paraguay": "PY",
	"Palestine": "PS",
	"Estonia": "EE",
	"Lebanon": "LB",
	"Qatar": "QA",
	"Kuwait": "KW",
	"Cambodia": "KH",
	"Nepal": "NP",
	"Luxembourg": "LU",
	"Bosnia": "BA",
	"Europe": "EU",
	"Asia": "ASIA",
	"International": "INT" 
}

AVAILABLE_COUNTRY = list(REGION_MAPPING.keys())


LANGUAGE_MAPPING = {
	'Arabic':'ar',
	'Chinese':'zh',
	'Dutch':'nl',
	'English':'en',
	'Finnish':'fi',
	'French':'fr',
	'German':'de',
	'Hindi':'hi',
	'Italian':'it',
	'Japanese':'ja',
	'Korean':'ko',
	'Malay':'msa',
	'Portuguese':'pt',
	'Russian':'ru',
	'Spanish':'es',
	'Vietnamise': 'vi',
	'Danish': 'da',
	'Czech': 'cs',
	'Greek': 'el',
	'Hungarian': 'hu',
	'Serbian': 'sr',
	'Thai': 'th',
	'Turkish': 'tr',
}

AVAILABLE_LANGUAGE = list(LANGUAGE_MAPPING.keys())

VALID_CATEGORIES = [
    'regional',
    'technology',
    'lifestyle',
    'business',
    'general',
    'programming',
    'science',
    'entertainment',
    'world',
    'sports',
    'finance',
    'academia',
    'politics',
    'health',
    'opinion',
    'food',
    'game',
    'fashion',
    'academic',
    'crap',
    'travel',
    'culture',
    'economy',
    'environment',
    'art',
    'music',
    'notsure',
    'CS',
    'education',
    'redundant',
    'television',
    'commodity',
    'movie',
    'entrepreneur',
    'review',
    'auto',
    'energy',
    'celebrity',
    'medical',
    'gadgets',
    'design',
    'EE',
    'security',
    'mobile',
    'estate',
    'funny'
]

sort_method = {'start_date','page_number','end_date'}
